services:
  app:
    build:
      context: .
      target: local
    command: ["npm", "run", "dev"]
    environment:
      DB_URL: /data/data.db
    ports:
      - 4173:4173 # http://localhost:4173 - Preview
      - 5173:5173 # http://localhost:5173 - Dev
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
      - ${LOCAL_WORKSPACE_FOLDER:-.}/volumes/data:/data
  # chromium:
  #   image: selenium/standalone-chromium:145.0-20260222
  #   shm_size: 2g
  #   environment:
  #     SE_VNC_NO_PASSWORD: true
  #     SE_BROWSER_ARGS_NO_SANDBOX: --no-sandbox
  #   ports:
  #     - 4444:4444 # http://localhost:4444 - Selenium Grid
  #     - 7900:7900 # http://localhost:4444 - VNC
