services:
  app:
    build:
      context: .
      target: local
    ports:
      - 4173:4173 # http://localhost:4173 - Preview
      - 5173:5173 # http://localhost:5173 - Dev
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/app
