# https://gitea.internal.alaeron.com/alaeron/infra-config/actions
name: tests
run-name: ${{ forge.actor }} opened pull request.
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  IMAGE_URI: gitea.internal.alaeron.com/alaeron/pf2e-combat-tracker
  IMAGE_BASE_VERSION: dev-v0.0
  # TRIVY_DISABLE_VEX_NOTICE: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: "Build image: dev"
        run: |
          docker compose -f docker-compose.ci.yaml build

      - name: "Debug"
        run: |
          env

      - name: "Run image"
        run: |
          docker compose -f docker-compose.ci.yaml up -d
  scan:
    runs-on: ${{ needs.build.outputs.RUNNER }}
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    needs:
      - build
    steps:
      - name: Scan image
        uses: https://github.com/aquasecurity/trivy-action@0.35.0
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE_URI }}:${{ env.IMAGE_BASE_VERSION }}.${{ forge.run_number }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          scanners: vuln,secret
          severity: CRITICAL,HIGH
          token-setup-trivy: ${{ secrets.PUBLIC_RO_GITHUB_ACCESS_TOKEN }}

  a11y:
    runs-on: ${{ needs.build.outputs.RUNNER }}
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    needs:
      - build
    steps:
      - name: "Test: a11y"
        run: |
          docker compose -f docker-compose.ci.yaml exec app npm run check:a11y

  post:
    runs-on: ${{ needs.build.outputs.RUNNER }}
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    needs:
      - build
      - scan
      - a11y
    if: ${{ always() }}
    steps:
      - name: "Cleanup"
        run: |
          docker compose -f docker-compose.ci.yaml down --remove-orphans

      - name: Job status
        run: |
          echo "Successfully ran all tests!"
